// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Models;
using Soenneker.Lemlist.OpenApiClient.V2.Tasks.Filters;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.V2.Tasks
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\tasks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filters property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.Filters.FiltersRequestBuilder Filters
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.Filters.FiltersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tasks{?advancedFilters*,assignedTo*,assignedToNot*,campaignId*,campaignIdNot*,channel*,companyId*,companyIdNot*,completedAtFrom*,completedAtTo*,contactId*,contactIdNot*,contactLinkedinUrl*,dueDateFrom*,dueDateTo*,hasCampaign*,hasDueDate*,include*,leadId*,leadIdNot*,limit*,objectType*,page*,priority*,search*,sortBy*,sortOrder*,status*,taskId*,title*,type*,typeNot*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/tasks{?advancedFilters*,assignedTo*,assignedToNot*,campaignId*,campaignIdNot*,channel*,companyId*,companyIdNot*,completedAtFrom*,completedAtTo*,contactId*,contactIdNot*,contactLinkedinUrl*,dueDateFrom*,dueDateTo*,hasCampaign*,hasDueDate*,include*,leadId*,leadIdNot*,limit*,objectType*,page*,priority*,search*,sortBy*,sortOrder*,status*,taskId*,title*,type*,typeNot*}", rawUrl)
        {
        }
        /// <summary>
        /// Searches the team&apos;s tasks with the same vocabulary as the Tasks page: flat query parameters for the common filters, and an `advancedFilters` tree for everything else. Every status is returned unless `status` narrows it.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2ListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetV2Tasks405Response">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2ListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2ListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Lemlist.OpenApiClient.Models.GetV2Tasks405Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2ListResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.TaskV2ListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Searches the team&apos;s tasks with the same vocabulary as the Tasks page: flat query parameters for the common filters, and an `advancedFilters` tree for everything else. Every status is returned unless `status` narrows it.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.V2.Tasks.TasksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Searches the team&apos;s tasks with the same vocabulary as the Tasks page: flat query parameters for the common filters, and an `advancedFilters` tree for everything else. Every status is returned unless `status` narrows it.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderGetQueryParameters 
        {
            /// <summary>A filter tree encoded as JSON, addressing any field returned by `GET /v2/tasks/filters`. Max depth 5, max 50 conditions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("advancedFilters")]
            public string? AdvancedFilters { get; set; }
#nullable restore
#else
            [QueryParameter("advancedFilters")]
            public string AdvancedFilters { get; set; }
#endif
            /// <summary>Ids of the users the task is assigned to. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("assignedTo")]
            public string? AssignedTo { get; set; }
#nullable restore
#else
            [QueryParameter("assignedTo")]
            public string AssignedTo { get; set; }
#endif
            /// <summary>Excludes the given `assignedTo` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("assignedToNot")]
            public string? AssignedToNot { get; set; }
#nullable restore
#else
            [QueryParameter("assignedToNot")]
            public string AssignedToNot { get; set; }
#endif
            /// <summary>Campaign ids. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("campaignId")]
            public string? CampaignId { get; set; }
#nullable restore
#else
            [QueryParameter("campaignId")]
            public string CampaignId { get; set; }
#endif
            /// <summary>Excludes the given `campaignId` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("campaignIdNot")]
            public string? CampaignIdNot { get; set; }
#nullable restore
#else
            [QueryParameter("campaignIdNot")]
            public string CampaignIdNot { get; set; }
#endif
            /// <summary>Channel the task belongs to — the coarser nomenclature shown in the app as &quot;Task type&quot;.</summary>
            [QueryParameter("channel")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksChannelParameter? Channel { get; set; }
            /// <summary>Company ids. Matches company-level tasks AND tasks on that company&apos;s contacts. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companyId")]
            public string? CompanyId { get; set; }
#nullable restore
#else
            [QueryParameter("companyId")]
            public string CompanyId { get; set; }
#endif
            /// <summary>Excludes the given `companyId` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companyIdNot")]
            public string? CompanyIdNot { get; set; }
#nullable restore
#else
            [QueryParameter("companyIdNot")]
            public string CompanyIdNot { get; set; }
#endif
            /// <summary>Lower bound of the completion date (done or ignored), inclusive. ISO-8601.</summary>
            [QueryParameter("completedAtFrom")]
            public DateTimeOffset? CompletedAtFrom { get; set; }
            /// <summary>Upper bound of the completion date (done or ignored), inclusive. ISO-8601.</summary>
            [QueryParameter("completedAtTo")]
            public DateTimeOffset? CompletedAtTo { get; set; }
            /// <summary>Contact ids. A single id also matches the tasks of that contact&apos;s leads, exactly like the contact panel does. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("contactId")]
            public string? ContactId { get; set; }
#nullable restore
#else
            [QueryParameter("contactId")]
            public string ContactId { get; set; }
#endif
            /// <summary>Excludes the given `contactId` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("contactIdNot")]
            public string? ContactIdNot { get; set; }
#nullable restore
#else
            [QueryParameter("contactIdNot")]
            public string ContactIdNot { get; set; }
#endif
            /// <summary>Matches tasks whose contact&apos;s LinkedIn URL contains this text. v1&apos;s `linkedin` filter matched the lead&apos;s URL instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("contactLinkedinUrl")]
            public string? ContactLinkedinUrl { get; set; }
#nullable restore
#else
            [QueryParameter("contactLinkedinUrl")]
            public string ContactLinkedinUrl { get; set; }
#endif
            /// <summary>Lower bound of the due date, inclusive. ISO-8601.</summary>
            [QueryParameter("dueDateFrom")]
            public DateTimeOffset? DueDateFrom { get; set; }
            /// <summary>Upper bound of the due date, inclusive. ISO-8601.</summary>
            [QueryParameter("dueDateTo")]
            public DateTimeOffset? DueDateTo { get; set; }
            /// <summary>Restricts to the tasks attached to a campaign (`true`) or to the standalone ones (`false`).</summary>
            [QueryParameter("hasCampaign")]
            public bool? HasCampaign { get; set; }
            /// <summary>Restricts to the tasks carrying a due date (`true`) or to those without one (`false`).</summary>
            [QueryParameter("hasDueDate")]
            public bool? HasDueDate { get; set; }
            /// <summary>Embeds the denormalized objects already carried by the task. Comma-separated.</summary>
            [QueryParameter("include")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksIncludeParameter? Include { get; set; }
            /// <summary>Lead ids. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("leadId")]
            public string? LeadId { get; set; }
#nullable restore
#else
            [QueryParameter("leadId")]
            public string LeadId { get; set; }
#endif
            /// <summary>Excludes the given `leadId` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("leadIdNot")]
            public string? LeadIdNot { get; set; }
#nullable restore
#else
            [QueryParameter("leadIdNot")]
            public string LeadIdNot { get; set; }
#endif
            /// <summary>Page size.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Restricts to the tasks hanging off a contact (a `contactId` or a `leadId` is present) or off a company (a `companyId` with no contact and no lead). Derived from the ids, never stored.</summary>
            [QueryParameter("objectType")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksObjectTypeParameter? ObjectType { get; set; }
            /// <summary>Page number, 1-based. `page * limit` must not exceed 10000.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Task priorities (integers), comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("priority")]
            public string? Priority { get; set; }
#nullable restore
#else
            [QueryParameter("priority")]
            public string Priority { get; set; }
#endif
            /// <summary>Free-text search over the task title and the contact / company text fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Field to sort on.</summary>
            [QueryParameter("sortBy")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksSortByParameter? SortBy { get; set; }
            /// <summary>Sort direction.</summary>
            [QueryParameter("sortOrder")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksSortOrderParameter? SortOrder { get; set; }
            /// <summary>Task statuses, comma-separated. `pending` is an alias for `due,upcoming,paused`. Unlike v1, completed tasks are returned unless you filter them out.</summary>
            [QueryParameter("status")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2TasksStatusParameter? Status { get; set; }
            /// <summary>Task ids. At most 100. Several values (comma-separated or repeated) are OR-ed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("taskId")]
            public string? TaskId { get; set; }
#nullable restore
#else
            [QueryParameter("taskId")]
            public string TaskId { get; set; }
#endif
            /// <summary>Matches tasks whose title contains this text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("title")]
            public string? Title { get; set; }
#nullable restore
#else
            [QueryParameter("title")]
            public string Title { get; set; }
#endif
            /// <summary>Raw step types, comma-separated. This is the same vocabulary as v1 `type`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
            /// <summary>Excludes the given `type` values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("typeNot")]
            public string? TypeNot { get; set; }
#nullable restore
#else
            [QueryParameter("typeNot")]
            public string TypeNot { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
