// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item.Entities;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts\lists\{listId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithListItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The entities property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item.Entities.EntitiesRequestBuilder Entities
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item.Entities.EntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item.WithListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithListItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/lists/{listId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.Item.WithListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithListItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/lists/{listId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
