// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.MessageTemplates.Item;
using Soenneker.Lemlist.OpenApiClient.MessageTemplates.Tags;
using Soenneker.Lemlist.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.MessageTemplates
{
    /// <summary>
    /// Builds and executes requests for operations under \message-templates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessageTemplatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tags property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.messageTemplates.item collection</summary>
        /// <param name="position">The unique identifier of the message template, from GET /message-templates</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.Item.WithTemplateItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.Item.WithTemplateItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("templateId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.Item.WithTemplateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessageTemplatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/message-templates{?limit*,page*,search*,tags*,userIds*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessageTemplatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/message-templates{?limit*,page*,search*,tags*,userIds*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the team&apos;s library message templates (the templates of the Templates page), newest first, with the page&apos;s own filters: a name search, tags and creators. Campaign step bodies are not templates: read them from GET /campaigns/{campaignId}/sequences.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.MessageTemplateListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetMessageTemplates400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplateListResponse401Error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.MessageTemplateListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder.MessageTemplatesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.MessageTemplateListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder.MessageTemplatesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.GetMessageTemplates400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplateListResponse401Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.MessageTemplateListResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.MessageTemplateListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the team&apos;s library message templates (the templates of the Templates page), newest first, with the page&apos;s own filters: a name search, tags and creators. Campaign step bodies are not templates: read them from GET /campaigns/{campaignId}/sequences.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder.MessageTemplatesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder.MessageTemplatesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.MessageTemplates.MessageTemplatesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the team&apos;s library message templates (the templates of the Templates page), newest first, with the page&apos;s own filters: a name search, tags and creators. Campaign step bodies are not templates: read them from GET /campaigns/{campaignId}/sequences.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MessageTemplatesRequestBuilderGetQueryParameters 
        {
            /// <summary>Number of items per page. Maximum value: 100</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Page number to retrieve, starting at 1</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Substring of the name, case-insensitive. Accented a, c, e, i, n, o, u, y match their plain letters (`relance` finds `Rélance`). Names only: bodies and subjects are not searched. Maximum 100 characters; a blank value is no filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Keep the templates carrying any of these tags. Comma-separated; the parameter may also be repeated (`?tags=a&amp;tags=b`), which keeps a comma inside a tag reachable. Tags are matched trimmed and lowercased, as the library stores them. Maximum 20.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string Tags { get; set; }
#endif
            /// <summary>Keep the items created by any of these users (`usr_` ids, see GET /team/members). Comma-separated; the parameter may also be repeated. Maximum 100. Omit for every creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("userIds")]
            public string? UserIds { get; set; }
#nullable restore
#else
            [QueryParameter("userIds")]
            public string UserIds { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
