// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Item;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Leads;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Start;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export
{
    /// <summary>
    /// Builds and executes requests for operations under \campaigns\{campaignId}\export
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The leads property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Leads.LeadsRequestBuilder Leads
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Leads.LeadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Start.StartRequestBuilder Start
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.campaigns.item.export.item collection</summary>
        /// <param name="position">The unique identifier of the export returned by the /start endpoint</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Item.WithExportItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Item.WithExportItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("exportId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.Item.WithExportItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/export", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/export", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
