// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Contacts.Export;
using Soenneker.Lemlist.OpenApiClient.Contacts.Item;
using Soenneker.Lemlist.OpenApiClient.Contacts.Lists;
using Soenneker.Lemlist.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Contacts
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.Export.ExportRequestBuilder Export
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Contacts.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.ListsRequestBuilder Lists
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Contacts.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.contacts.item collection</summary>
        /// <param name="position">The unique identifier or email of the contact</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.Item.WithIdOrEmailItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.Item.WithIdOrEmailItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("idOrEmail", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Contacts.Item.WithIdOrEmailItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts{?companyDomain*,companyId*,companyLinkedinUrl*,companySalesnavUrl*,email*,fieldRejectionReason*,idsOrEmails,limit*,listId*,notInAnyCampaign*,offset*,search*,withPrimaryCompany*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts{?companyDomain*,companyId*,companyLinkedinUrl*,companySalesnavUrl*,email*,fieldRejectionReason*,idsOrEmails,limit*,listId*,notInAnyCampaign*,offset*,search*,withPrimaryCompany*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves contacts by IDs/emails, or searches/lists contacts by name, email, contact list, campaign membership, or company link.When using `idsOrEmails`, returns an array of matching contacts directly.When using `search`, `email`, `listId`, `notInAnyCampaign`, any of the `company*` filters, or no filter at all, returns a paginated response with `data`, `total`, `limit`, and `offset` fields. You can combine filters together to narrow results (e.g. `listId` with `search`, or `notInAnyCampaign` with `companyId`). Calling the endpoint without any filter returns all contacts of the team, paginated.The `company*` filters (`companyId`, `companyDomain`, `companyLinkedinUrl`, `companySalesnavUrl`) are mutually exclusive — use only one at a time. `companyDomain` / `companyLinkedinUrl` / `companySalesnavUrl` are resolved to a `companyId` through the Companies collection; if no matching company exists, the endpoint returns an empty list with `total: 0` (not an error), which keeps automation flows simple.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetContacts200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.GetContacts200Response400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.GetContacts200Response401Error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.GetContacts200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.GetContacts200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Contacts.GetContacts200Response400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Contacts.GetContacts200Response401Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.GetContacts200Response>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.GetContacts200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new contact or updates an existing one (upsert). If a contact with the same email, LinkedIn URL, or Sales Navigator URL already exists, it will be updated with the provided non-empty fields. Null or empty values are ignored during updates to preserve existing data. You can target an existing contact directly by providing `contactId`, bypassing email/LinkedIn matching. You can optionally link the contact to a company by providing `companyId`, `companyDomain`, or `companyLinkedinUrl`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.PostContacts200Response401Error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts200Response?> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts200Response> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Contacts.PostContacts200Response401Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts200Response>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.PostContacts200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves contacts by IDs/emails, or searches/lists contacts by name, email, contact list, campaign membership, or company link.When using `idsOrEmails`, returns an array of matching contacts directly.When using `search`, `email`, `listId`, `notInAnyCampaign`, any of the `company*` filters, or no filter at all, returns a paginated response with `data`, `total`, `limit`, and `offset` fields. You can combine filters together to narrow results (e.g. `listId` with `search`, or `notInAnyCampaign` with `companyId`). Calling the endpoint without any filter returns all contacts of the team, paginated.The `company*` filters (`companyId`, `companyDomain`, `companyLinkedinUrl`, `companySalesnavUrl`) are mutually exclusive — use only one at a time. `companyDomain` / `companyLinkedinUrl` / `companySalesnavUrl` are resolved to a `companyId` through the Companies collection; if no matching company exists, the endpoint returns an empty list with `total: 0` (not an error), which keeps automation flows simple.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new contact or updates an existing one (upsert). If a contact with the same email, LinkedIn URL, or Sales Navigator URL already exists, it will be updated with the provided non-empty fields. Null or empty values are ignored during updates to preserve existing data. You can target an existing contact directly by providing `contactId`, bypassing email/LinkedIn matching. You can optionally link the contact to a company by providing `companyId`, `companyDomain`, or `companyLinkedinUrl`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves contacts by IDs/emails, or searches/lists contacts by name, email, contact list, campaign membership, or company link.When using `idsOrEmails`, returns an array of matching contacts directly.When using `search`, `email`, `listId`, `notInAnyCampaign`, any of the `company*` filters, or no filter at all, returns a paginated response with `data`, `total`, `limit`, and `offset` fields. You can combine filters together to narrow results (e.g. `listId` with `search`, or `notInAnyCampaign` with `companyId`). Calling the endpoint without any filter returns all contacts of the team, paginated.The `company*` filters (`companyId`, `companyDomain`, `companyLinkedinUrl`, `companySalesnavUrl`) are mutually exclusive — use only one at a time. `companyDomain` / `companyLinkedinUrl` / `companySalesnavUrl` are resolved to a `companyId` through the Companies collection; if no matching company exists, the endpoint returns an empty list with `total: 0` (not an error), which keeps automation flows simple.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContactsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter contacts by their company&apos;s website domain. Resolved to a `companyId` against the Companies collection. If no company matches, the endpoint returns an empty list (`total: 0`). Mutually exclusive with the other `company*` filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companyDomain")]
            public string? CompanyDomain { get; set; }
#nullable restore
#else
            [QueryParameter("companyDomain")]
            public string CompanyDomain { get; set; }
#endif
            /// <summary>Filter contacts by attached company ID (`cpn_xxx` format). Use this when you already know the lemlist company id (for example after fetching `GET /companies?crmSyncStatus=unique_index_error_company`). Mutually exclusive with `companyDomain`, `companyLinkedinUrl`, and `companySalesnavUrl`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companyId")]
            public string? CompanyId { get; set; }
#nullable restore
#else
            [QueryParameter("companyId")]
            public string CompanyId { get; set; }
#endif
            /// <summary>Filter contacts by their company&apos;s LinkedIn URL. Resolved to a `companyId` against the Companies collection. If no company matches, the endpoint returns an empty list (`total: 0`). Mutually exclusive with the other `company*` filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companyLinkedinUrl")]
            public string? CompanyLinkedinUrl { get; set; }
#nullable restore
#else
            [QueryParameter("companyLinkedinUrl")]
            public string CompanyLinkedinUrl { get; set; }
#endif
            /// <summary>Filter contacts by their company&apos;s LinkedIn Sales Navigator URL. Resolved to a `companyId` against the Companies collection. If no company matches, the endpoint returns an empty list (`total: 0`). Mutually exclusive with the other `company*` filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("companySalesnavUrl")]
            public string? CompanySalesnavUrl { get; set; }
#nullable restore
#else
            [QueryParameter("companySalesnavUrl")]
            public string CompanySalesnavUrl { get; set; }
#endif
            /// <summary>Search contacts by exact email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("email")]
            public string? Email { get; set; }
#nullable restore
#else
            [QueryParameter("email")]
            public string Email { get; set; }
#endif
            /// <summary>Filter contacts to those carrying a field rejection with this reason — a value lemlist refused to write, prefixed by its origin (`enrichment_*` while enriching, `crm_sync_*` during CRM sync). Returns an empty list (`total: 0`) when no contact matches. Each returned contact exposes the full detail under `fieldRejections[]` (which field, why, and `conflictingRecordId` for duplicates). Only applies to the paginated list — ignored when `idsOrEmails` is provided (that path returns the exact contacts requested, unfiltered).</summary>
            [QueryParameter("fieldRejectionReason")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetContactsFieldRejectionReasonParameter? FieldRejectionReason { get; set; }
            /// <summary>A comma separated string of either valid contact IDs (MongoDB ObjectId) or valid email addresses. Optional — when omitted, returns the paginated list of all contacts of the team. Maximum 100 values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("idsOrEmails")]
            public string? IdsOrEmails { get; set; }
#nullable restore
#else
            [QueryParameter("idsOrEmails")]
            public string IdsOrEmails { get; set; }
#endif
            /// <summary>Maximum number of contacts to return (1–500). Defaults to 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter contacts by contact list ID (`clt_xxx` format). Can be combined with `search` or `email`, or used alone to list all contacts in a list. Get valid IDs from `GET /contacts/lists`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("listId")]
            public string? ListId { get; set; }
#nullable restore
#else
            [QueryParameter("listId")]
            public string ListId { get; set; }
#endif
            /// <summary>When set to `true`, only returns contacts that are not part of any campaign (orphan contacts). Can be used alone or combined with other filters such as `search`, `email`, or `listId`.</summary>
            [QueryParameter("notInAnyCampaign")]
            public bool? NotInAnyCampaign { get; set; }
            /// <summary>Number of contacts to skip for pagination. Defaults to 0.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Search contacts by name or other text fields. Must be at least 2 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>When set to `true`, only returns contacts linked to a company; when set to `false`, only returns contacts without a company. Omit for no filter. Mutually exclusive with the `company*` filters (`companyId`, `companyDomain`, `companyLinkedinUrl`, `companySalesnavUrl`).</summary>
            [QueryParameter("withPrimaryCompany")]
            public bool? WithPrimaryCompany { get; set; }
        }
    }
}
#pragma warning restore CS0618
