// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\enrichments\providers\{providerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProviderItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connection property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder Connection
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/enrichments/providers/{providerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.WithProviderItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/enrichments/providers/{providerId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
