// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\enrichments\providers\{providerId}\connection
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/enrichments/providers/{providerId}/connection", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/enrichments/providers/{providerId}/connection", rawUrl)
        {
        }
        /// <summary>
        /// Removes your API key for an external provider. lemlist stops calling it on your account and removes it from your custom waterfalls.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Saves your own API key for an external provider. The key is stored as-is and is NOT validated against the provider; calling it again replaces the key. The provider is connected for every enrichment type it supports.Once connected, the provider is added, disabled, to your existing custom waterfalls.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse?> PutAsync(global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderConnectRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse> PutAsync(global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderConnectRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Removes your API key for an external provider. lemlist stops calling it on your account and removes it from your custom waterfalls.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Saves your own API key for an external provider. The key is stored as-is and is NOT validated against the provider; calling it again replaces the key. The provider is connected for every enrichment type it supports.Once connected, the provider is added, disabled, to your existing custom waterfalls.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderConnectRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderConnectRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.V2.Enrichments.Providers.Item.Connection.ConnectionRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
