// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Models;
using Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches
{
    /// <summary>
    /// Builds and executes requests for operations under \sequences\{sequenceId}\steps\{stepId}\branches
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BranchesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.sequences.item.steps.item.branches.item collection</summary>
        /// <param name="position">The branch&apos;s own sub-sequence id, from `GET /sequences/{sequenceId}/steps/{stepId}/branches`. A branch is never addressed by its position.</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.Item.WithBranchSequenceItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.Item.WithBranchSequenceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("branchSequenceId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.Item.WithBranchSequenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.BranchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences/{sequenceId}/steps/{stepId}/branches", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.BranchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BranchesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences/{sequenceId}/steps/{stepId}/branches", rawUrl)
        {
        }
        /// <summary>
        /// Every branch of a condition step, in execution order, with the Else branch last. A condition step holds an ordered list of branches, each owning the sub-sequence the leads it matches walk into. Array order is execution priority: the first branch whose test matches takes the lead, and the Else branch at the end catches everyone no branch matched. A branch is addressed by its `sequenceId`, never by position - a reorder moves positions, the sub-sequence id is what the runtime routes leads to.Reading branches is not gated; only the writes are in closed beta.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema404Error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema401Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema402Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.GetSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema404Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Rewrites the execution priority of a condition step&apos;s branches. Order is priority: the first branch whose test matches takes the lead.`order` must list every non-fallback branch of the step exactly once. The Else branch is not orderable and always stays last, so it is left out of the list. Sending the order the step already has is a no-op that still returns the branches.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema409Error">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>?> PatchAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PatchSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>> PatchAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PatchSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema401Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema402Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.PatchSequencesBySequenceIdStepsByStepIdBranches200ResponseSchema409Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Adds a branch to a condition step, just before the Else branch, and mints the empty sub-sequence it routes to. Add steps to that branch by calling `POST /sequences/{sequenceId}/steps` with the returned `sequenceId`.A branch carries the value it tests from the moment it is created - there are no blank branches - so the body must say what this one matches. The step&apos;s condition is shared by every branch and is never sent here: `conditionKey` in the body is refused.Only four conditions host several branches: `customLeadInfo`, `hasScore`, `hasEmailAddress` and `aircallDone`. Each needs its own tested value in the body, except `hasScore`, whose new branch inherits a complete `&gt;= 80` band and can be added from an empty body.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch409Error">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch?> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch401Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch402Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch404Error.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.ConditionBranch409Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.ConditionBranch.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Every branch of a condition step, in execution order, with the Else branch last. A condition step holds an ordered list of branches, each owning the sub-sequence the leads it matches walk into. Array order is execution priority: the first branch whose test matches takes the lead, and the Else branch at the end catches everyone no branch matched. A branch is addressed by its `sequenceId`, never by position - a reorder moves positions, the sub-sequence id is what the runtime routes leads to.Reading branches is not gated; only the writes are in closed beta.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Rewrites the execution priority of a condition step&apos;s branches. Order is priority: the first branch whose test matches takes the lead.`order` must list every non-fallback branch of the step exactly once. The Else branch is not orderable and always stays last, so it is left out of the list. Sending the order the step already has is a no-op that still returns the branches.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PatchSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PatchSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Adds a branch to a condition step, just before the Else branch, and mints the empty sub-sequence it routes to. Add steps to that branch by calling `POST /sequences/{sequenceId}/steps` with the returned `sequenceId`.A branch carries the value it tests from the moment it is created - there are no blank branches - so the body must say what this one matches. The step&apos;s condition is shared by every branch and is never sent here: `conditionKey` in the body is refused.Only four conditions host several branches: `customLeadInfo`, `hasScore`, `hasEmailAddress` and `aircallDone`. Each needs its own tested value in the body, except `hasScore`, whose new branch inherits a complete `&gt;= 80` band and can be added from an empty body.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostSequencesBySequenceIdStepsByStepIdBranchesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.BranchesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.BranchesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.Item.Branches.BranchesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
