// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Models;
using Soenneker.Lemlist.OpenApiClient.Team.Credits;
using Soenneker.Lemlist.OpenApiClient.Team.CrmUsers;
using Soenneker.Lemlist.OpenApiClient.Team.Senders;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Team
{
    /// <summary>
    /// Builds and executes requests for operations under \team
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TeamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The credits property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Team.Credits.CreditsRequestBuilder Credits
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Team.Credits.CreditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The crmUsers property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Team.CrmUsers.CrmUsersRequestBuilder CrmUsers
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Team.CrmUsers.CrmUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The senders property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Team.Senders.SendersRequestBuilder Senders
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Team.Senders.SendersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/team{?version*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/team{?version*}", rawUrl)
        {
        }
        /// <summary>
        /// Get Team
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.Team"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Team.Team400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Team.Team401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Team.Team403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Team.Team404Error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.Team?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder.TeamRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.Team> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder.TeamRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Team.Team400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Team.Team401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Lemlist.OpenApiClient.Team.Team403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Team.Team404Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.Team>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.Team.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Team
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder.TeamRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder.TeamRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Team
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TeamRequestBuilderGetQueryParameters 
        {
            /// <summary>Set to `v2` to include the `users` array, listing each team member&apos;s `userId`, `name`, `email`, and `role`. This lets you retrieve the team and its members in a single request.</summary>
            [QueryParameter("version")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.V2Version? Version { get; set; }
        }
    }
}
#pragma warning restore CS0618
