// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Import;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item;
using Soenneker.Lemlist.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads
{
    /// <summary>
    /// Builds and executes requests for operations under \campaigns\{campaignId}\leads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LeadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The import property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Import.ImportRequestBuilder Import
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Import.ImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.campaigns.item.leads.item collection</summary>
        /// <param name="position">The unique identifier of the lead</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.LeadIdOrEmailItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.LeadIdOrEmailItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("leadIdOrEmail%2Did", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.LeadIdOrEmailItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/leads{?deduplicate*,findEmail*,findPhone*,limit*,linkedinEnrichment*,state*,verifyEmail*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/leads{?deduplicate*,findEmail*,findPhone*,limit*,linkedinEnrichment*,state*,verifyEmail*}", rawUrl)
        {
        }
        /// <summary>
        /// Unsubscribe Lead from Campaign
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.DeleteCampaignsByCampaignIdLeads200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.DeleteCampaignsByCampaignIdLeads200Response400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.DeleteCampaignsByCampaignIdLeads200Response404Error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.DeleteCampaignsByCampaignIdLeads200Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.DeleteCampaignsByCampaignIdLeads200Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.DeleteCampaignsByCampaignIdLeads200Response400Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.DeleteCampaignsByCampaignIdLeads200Response404Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.DeleteCampaignsByCampaignIdLeads200Response>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.DeleteCampaignsByCampaignIdLeads200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Campaign Leads
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Lemlist.OpenApiClient.Models.GetCampaignsByCampaignIdLeads200ResponseSchemaItem&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.GetCampaignsByCampaignIdLeads200ResponseSchemaItem>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Lemlist.OpenApiClient.Models.GetCampaignsByCampaignIdLeads200ResponseSchemaItem>> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Lemlist.OpenApiClient.Models.GetCampaignsByCampaignIdLeads200ResponseSchemaItem>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.GetCampaignsByCampaignIdLeads200ResponseSchemaItem.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create Lead in Campaign
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeads200Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response404Error">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeads200Response?> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeadsRequest body, Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeads200Response> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeadsRequest body, Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.PostCampaignsByCampaignIdLeads200Response404Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeads200Response>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeads200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Unsubscribe Lead from Campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get Campaign Leads
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create Lead in Campaign
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeadsRequest body, Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaignsByCampaignIdLeadsRequest body, Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder.LeadsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.LeadsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Campaign Leads
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LeadsRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum number of leads to return. Default: 100, Max: 500</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter leads by state (e.g., scanned, contacted, interested, notInterested, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
        }
        /// <summary>
        /// Create Lead in Campaign
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LeadsRequestBuilderPostQueryParameters 
        {
            /// <summary>Search email address in other campaigns. Will not insert the lead if email address already exists. Default: false</summary>
            [QueryParameter("deduplicate")]
            public bool? Deduplicate { get; set; }
            /// <summary>Find verified email. Default: false</summary>
            [QueryParameter("findEmail")]
            public bool? FindEmail { get; set; }
            /// <summary>Find phone number. Default: false</summary>
            [QueryParameter("findPhone")]
            public bool? FindPhone { get; set; }
            /// <summary>Run the LinkedIn enrichment. Default: false</summary>
            [QueryParameter("linkedinEnrichment")]
            public bool? LinkedinEnrichment { get; set; }
            /// <summary>Verify existing email (debounce). Default: false</summary>
            [QueryParameter("verifyEmail")]
            public bool? VerifyEmail { get; set; }
        }
    }
}
#pragma warning restore CS0618
