// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Active CRM provider for the team.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CompanyCrmSyncProvider
    {
        [EnumMember(Value = "hubspot")]
        #pragma warning disable CS1591
        Hubspot,
        #pragma warning restore CS1591
        [EnumMember(Value = "salesforce")]
        #pragma warning disable CS1591
        Salesforce,
        #pragma warning restore CS1591
        [EnumMember(Value = "pipedrive")]
        #pragma warning disable CS1591
        Pipedrive,
        #pragma warning restore CS1591
    }
}
