// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Customer type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CompaniesSchemaBusinessBusinessCustomer
    {
        [EnumMember(Value = "B2B")]
        #pragma warning disable CS1591
        B2B,
        #pragma warning restore CS1591
        [EnumMember(Value = "B2C")]
        #pragma warning disable CS1591
        B2C,
        #pragma warning restore CS1591
        [EnumMember(Value = "B2B2C")]
        #pragma warning disable CS1591
        B2B2C,
        #pragma warning restore CS1591
    }
}
