// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// A company record from lemlist&apos;s Companies database.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompaniesSchema : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Customer type</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchemaBusinessBusinessCustomer? BusinessBusinessCustomer { get; set; }
        /// <summary>Long company description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyDescription { get; set; }
#nullable restore
#else
        public string CompanyDescription { get; set; }
#endif
        /// <summary>Company web domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyDomain { get; set; }
#nullable restore
#else
        public string CompanyDomain { get; set; }
#endif
        /// <summary>Employee count as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyEmployeeCount { get; set; }
#nullable restore
#else
        public string CompanyEmployeeCount { get; set; }
#endif
        /// <summary>LinkedIn followers count as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyFollowersCount { get; set; }
#nullable restore
#else
        public string CompanyFollowersCount { get; set; }
#endif
        /// <summary>Year founded as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyFounded { get; set; }
#nullable restore
#else
        public string CompanyFounded { get; set; }
#endif
        /// <summary>Headquarters city</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyHeadquartersCity { get; set; }
#nullable restore
#else
        public string CompanyHeadquartersCity { get; set; }
#endif
        /// <summary>Headquarters country</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyHeadquartersCountry { get; set; }
#nullable restore
#else
        public string CompanyHeadquartersCountry { get; set; }
#endif
        /// <summary>Unique company identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyId { get; set; }
#nullable restore
#else
        public string CompanyId { get; set; }
#endif
        /// <summary>Primary industry</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyIndustry { get; set; }
#nullable restore
#else
        public string CompanyIndustry { get; set; }
#endif
        /// <summary>LinkedIn company profile URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyLinkedinUrl { get; set; }
#nullable restore
#else
        public string CompanyLinkedinUrl { get; set; }
#endif
        /// <summary>Full formatted location</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyLocation { get; set; }
#nullable restore
#else
        public string CompanyLocation { get; set; }
#endif
        /// <summary>Geopoint coordinates [longitude, latitude]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? CompanyLocationGeopointArray { get; set; }
#nullable restore
#else
        public List<double?> CompanyLocationGeopointArray { get; set; }
#endif
        /// <summary>Company logo image URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyLogoUrl { get; set; }
#nullable restore
#else
        public string CompanyLogoUrl { get; set; }
#endif
        /// <summary>Company name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>Occupational lead count as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyOccLead { get; set; }
#nullable restore
#else
        public string CompanyOccLead { get; set; }
#endif
        /// <summary>Quality score as string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyQualityScore { get; set; }
#nullable restore
#else
        public string CompanyQualityScore { get; set; }
#endif
        /// <summary>Company size bucket</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanySize { get; set; }
#nullable restore
#else
        public string CompanySize { get; set; }
#endif
        /// <summary>Sub-industry</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanySubindustry { get; set; }
#nullable restore
#else
        public string CompanySubindustry { get; set; }
#endif
        /// <summary>Sub-sub-industry</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanySubsubindustry { get; set; }
#nullable restore
#else
        public string CompanySubsubindustry { get; set; }
#endif
        /// <summary>Company type (e.g., Privately Held, Public Company)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyType { get; set; }
#nullable restore
#else
        public string CompanyType { get; set; }
#endif
        /// <summary>Official company website URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyWebsiteUrl { get; set; }
#nullable restore
#else
        public string CompanyWebsiteUrl { get; set; }
#endif
        /// <summary>Employee count growth number</summary>
        public int? EmployeesCountGrowth { get; set; }
        /// <summary>Internal document ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Date of last funding round</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastFundingRoundAt { get; set; }
#nullable restore
#else
        public string LastFundingRoundAt { get; set; }
#endif
        /// <summary>Last update timestamp (UTC)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdated { get; set; }
#nullable restore
#else
        public string LastUpdated { get; set; }
#endif
        /// <summary>Revenue range bucket</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RevenueBucket { get; set; }
#nullable restore
#else
        public string RevenueBucket { get; set; }
#endif
        /// <summary>Search relevance score</summary>
        public double? Score { get; set; }
        /// <summary>Array of technologies used by the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TechnoUsedArray { get; set; }
#nullable restore
#else
        public List<string> TechnoUsedArray { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchema"/> and sets the default values.
        /// </summary>
        public CompaniesSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "business_business_customer", n => { BusinessBusinessCustomer = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchemaBusinessBusinessCustomer>(); } },
                { "company_description", n => { CompanyDescription = n.GetStringValue(); } },
                { "company_domain", n => { CompanyDomain = n.GetStringValue(); } },
                { "company_employee_count", n => { CompanyEmployeeCount = n.GetStringValue(); } },
                { "company_followers_count", n => { CompanyFollowersCount = n.GetStringValue(); } },
                { "company_founded", n => { CompanyFounded = n.GetStringValue(); } },
                { "company_headquarters_city", n => { CompanyHeadquartersCity = n.GetStringValue(); } },
                { "company_headquarters_country", n => { CompanyHeadquartersCountry = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetStringValue(); } },
                { "company_industry", n => { CompanyIndustry = n.GetStringValue(); } },
                { "company_linkedin_url", n => { CompanyLinkedinUrl = n.GetStringValue(); } },
                { "company_location", n => { CompanyLocation = n.GetStringValue(); } },
                { "company_location_geopoint_array", n => { CompanyLocationGeopointArray = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "company_logo_url", n => { CompanyLogoUrl = n.GetStringValue(); } },
                { "company_name", n => { CompanyName = n.GetStringValue(); } },
                { "company_occ_lead", n => { CompanyOccLead = n.GetStringValue(); } },
                { "company_quality_score", n => { CompanyQualityScore = n.GetStringValue(); } },
                { "company_size", n => { CompanySize = n.GetStringValue(); } },
                { "company_subindustry", n => { CompanySubindustry = n.GetStringValue(); } },
                { "company_subsubindustry", n => { CompanySubsubindustry = n.GetStringValue(); } },
                { "company_type", n => { CompanyType = n.GetStringValue(); } },
                { "company_website_url", n => { CompanyWebsiteUrl = n.GetStringValue(); } },
                { "employees_count_growth", n => { EmployeesCountGrowth = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "last_funding_round_at", n => { LastFundingRoundAt = n.GetStringValue(); } },
                { "last_updated", n => { LastUpdated = n.GetStringValue(); } },
                { "revenue_bucket", n => { RevenueBucket = n.GetStringValue(); } },
                { "_score", n => { Score = n.GetDoubleValue(); } },
                { "techno_used_array", n => { TechnoUsedArray = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.CompaniesSchemaBusinessBusinessCustomer>("business_business_customer", BusinessBusinessCustomer);
            writer.WriteStringValue("company_description", CompanyDescription);
            writer.WriteStringValue("company_domain", CompanyDomain);
            writer.WriteStringValue("company_employee_count", CompanyEmployeeCount);
            writer.WriteStringValue("company_followers_count", CompanyFollowersCount);
            writer.WriteStringValue("company_founded", CompanyFounded);
            writer.WriteStringValue("company_headquarters_city", CompanyHeadquartersCity);
            writer.WriteStringValue("company_headquarters_country", CompanyHeadquartersCountry);
            writer.WriteStringValue("company_id", CompanyId);
            writer.WriteStringValue("company_industry", CompanyIndustry);
            writer.WriteStringValue("company_linkedin_url", CompanyLinkedinUrl);
            writer.WriteStringValue("company_location", CompanyLocation);
            writer.WriteCollectionOfPrimitiveValues<double?>("company_location_geopoint_array", CompanyLocationGeopointArray);
            writer.WriteStringValue("company_logo_url", CompanyLogoUrl);
            writer.WriteStringValue("company_name", CompanyName);
            writer.WriteStringValue("company_occ_lead", CompanyOccLead);
            writer.WriteStringValue("company_quality_score", CompanyQualityScore);
            writer.WriteStringValue("company_size", CompanySize);
            writer.WriteStringValue("company_subindustry", CompanySubindustry);
            writer.WriteStringValue("company_subsubindustry", CompanySubsubindustry);
            writer.WriteStringValue("company_type", CompanyType);
            writer.WriteStringValue("company_website_url", CompanyWebsiteUrl);
            writer.WriteIntValue("employees_count_growth", EmployeesCountGrowth);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("last_funding_round_at", LastFundingRoundAt);
            writer.WriteStringValue("last_updated", LastUpdated);
            writer.WriteStringValue("revenue_bucket", RevenueBucket);
            writer.WriteDoubleValue("_score", Score);
            writer.WriteCollectionOfPrimitiveValues<string>("techno_used_array", TechnoUsedArray);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
