// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Kind of input the filter expects. `level` is a two-level dropdown of the People Database UI; it is reported as `select` by default.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseFilterType
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
        [EnumMember(Value = "autocomplete")]
        #pragma warning disable CS1591
        Autocomplete,
        #pragma warning restore CS1591
        [EnumMember(Value = "static")]
        #pragma warning disable CS1591
        StaticValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "slider")]
        #pragma warning disable CS1591
        Slider,
        #pragma warning restore CS1591
        [EnumMember(Value = "level")]
        #pragma warning disable CS1591
        Level,
        #pragma warning restore CS1591
        [EnumMember(Value = "elasticId")]
        #pragma warning disable CS1591
        ElasticId,
        #pragma warning restore CS1591
    }
}
