// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// Notification channels triggered when the alert fires. At least one channel must be enabled. If omitted on creation, defaults to `inapp` only.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliverabilityAlertChannelConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigEmail? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigEmail Email { get; set; }
#endif
        /// <summary>The inapp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigInapp? Inapp { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigInapp Inapp { get; set; }
#endif
        /// <summary>The slack property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigSlack? Slack { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigSlack Slack { get; set; }
#endif
        /// <summary>The webhook property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigWebhook? Webhook { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigWebhook Webhook { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig"/> and sets the default values.
        /// </summary>
        public DeliverabilityAlertChannelConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigEmail>(global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigEmail.CreateFromDiscriminatorValue); } },
                { "inapp", n => { Inapp = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigInapp>(global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigInapp.CreateFromDiscriminatorValue); } },
                { "slack", n => { Slack = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigSlack>(global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigSlack.CreateFromDiscriminatorValue); } },
                { "webhook", n => { Webhook = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigWebhook>(global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigWebhook.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigEmail>("email", Email);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigInapp>("inapp", Inapp);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigSlack>("slack", Slack);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfigWebhook>("webhook", Webhook);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
