// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// A deliverability alert configuration. The alert is evaluated periodically against your warm-up or outreach metrics and triggers notifications through the configured channels (in-app, email, webhook, Slack) when the threshold is breached.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliverabilityAlert : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Notification channels triggered when the alert fires. At least one channel must be enabled. If omitted on creation, defaults to `inapp` only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig? ChannelConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig ChannelConfig { get; set; }
#endif
        /// <summary>How `threshold` is compared to the current value. `below` triggers when the value drops under the threshold; `above` triggers when it exceeds it; `equal` triggers on exact match.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertComparisonOperator? ComparisonOperator { get; set; }
        /// <summary>Creation timestamp.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>ID of the user who created the alert.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Whether the alert is currently active. Disabled alerts are not evaluated.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Unique alert configuration identifier (prefixed with `dac_`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Last time the alert was evaluated.</summary>
        public DateTimeOffset? LastCheckedAt { get; set; }
        /// <summary>Last time the alert fired.</summary>
        public DateTimeOffset? LastTriggeredAt { get; set; }
        /// <summary>Metric being monitored. Valid combinations depend on `widget`: `warmup` supports `inboxRate`, `spamRate`, `score`; `outreach` supports `deliveryRate`, `bounceRate`.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertMetric? Metric { get; set; }
        /// <summary>Length of the evaluation window, in days (1–30).</summary>
        public int? PeriodDays { get; set; }
        /// <summary>How the metric is computed over `periodDays`. `rolling` averages the metric across the window; `consecutive` requires the condition to hold on every one of the most recent `periodDays`.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertPeriodMode? PeriodMode { get; set; }
        /// <summary>Cool-down between re-evaluations after the alert has triggered, in hours. Defaults to 12.</summary>
        public int? RecheckDelayHours { get; set; }
        /// <summary>Aggregation level the metric is computed at. `global` covers all of the workspace&apos;s mailboxes (warm-up only); `mailbox` evaluates each mailbox individually; `domain` groups mailboxes by their sending domain.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertScope? Scope { get; set; }
        /// <summary>Restricts the alert to a subset of entities matching `scope`. When empty, all entities of that scope are checked. For `scope=mailbox`, each entry is a composite string `userId|email|mailboxId`. For `scope=domain`, each entry is a domain (e.g. `acme.com`). Ignored when `scope=global`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ScopeEntities { get; set; }
#nullable restore
#else
        public List<string> ScopeEntities { get; set; }
#endif
        /// <summary>Alert severity.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertSeverity? Severity { get; set; }
        /// <summary>ID of the team that owns the alert.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>Threshold value the metric is compared against (0–100, expressed as a percentage for rate metrics).</summary>
        public double? Threshold { get; set; }
        /// <summary>Last update timestamp.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Data source the alert evaluates. `warmup` checks lemwarm metrics; `outreach` checks campaign-sending metrics.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertWidget? Widget { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlert"/> and sets the default values.
        /// </summary>
        public DeliverabilityAlert()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlert"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlert CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlert();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channelConfig", n => { ChannelConfig = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig>(global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig.CreateFromDiscriminatorValue); } },
                { "comparisonOperator", n => { ComparisonOperator = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertComparisonOperator>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "lastCheckedAt", n => { LastCheckedAt = n.GetDateTimeOffsetValue(); } },
                { "lastTriggeredAt", n => { LastTriggeredAt = n.GetDateTimeOffsetValue(); } },
                { "metric", n => { Metric = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertMetric>(); } },
                { "periodDays", n => { PeriodDays = n.GetIntValue(); } },
                { "periodMode", n => { PeriodMode = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertPeriodMode>(); } },
                { "recheckDelayHours", n => { RecheckDelayHours = n.GetIntValue(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertScope>(); } },
                { "scopeEntities", n => { ScopeEntities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "severity", n => { Severity = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertSeverity>(); } },
                { "teamId", n => { TeamId = n.GetStringValue(); } },
                { "threshold", n => { Threshold = n.GetDoubleValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "widget", n => { Widget = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertWidget>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertChannelConfig>("channelConfig", ChannelConfig);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertComparisonOperator>("comparisonOperator", ComparisonOperator);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("_id", Id);
            writer.WriteDateTimeOffsetValue("lastCheckedAt", LastCheckedAt);
            writer.WriteDateTimeOffsetValue("lastTriggeredAt", LastTriggeredAt);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertMetric>("metric", Metric);
            writer.WriteIntValue("periodDays", PeriodDays);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertPeriodMode>("periodMode", PeriodMode);
            writer.WriteIntValue("recheckDelayHours", RecheckDelayHours);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertScope>("scope", Scope);
            writer.WriteCollectionOfPrimitiveValues<string>("scopeEntities", ScopeEntities);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertSeverity>("severity", Severity);
            writer.WriteStringValue("teamId", TeamId);
            writer.WriteDoubleValue("threshold", Threshold);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.DeliverabilityAlertWidget>("widget", Widget);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
