// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// A data provider your team can place in a waterfall.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnrichmentProvider : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only on external providers: `true` once its API key is saved in lemlist. A waterfall can only enable a connected provider.</summary>
        public bool? Connected { get; set; }
        /// <summary>Name shown in the lemlist app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Stable identifier, to use as `providers[].id` in the waterfall endpoints.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>`internal`: paid with lemlist credits, always available. `external`: called with your own API key, saved through the connection endpoint.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderSource? Source { get; set; }
        /// <summary>Enrichment types this provider supports.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallType?>? Types { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallType?> Types { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProvider"/> and sets the default values.
        /// </summary>
        public EnrichmentProvider()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProvider"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProvider CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProvider();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connected", n => { Connected = n.GetBoolValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderSource>(); } },
                { "types", n => { Types = n.GetCollectionOfEnumValues<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallType>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("connected", Connected);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentProviderSource>("source", Source);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Lemlist.OpenApiClient.Models.EnrichmentWaterfallType>("types", Types);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
