// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Why the signal was ignored. Present when status is ignored.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalSignalPushResponseReason
    {
        [EnumMember(Value = "no_entity_match")]
        #pragma warning disable CS1591
        NoEntityMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "daily_limit_reached")]
        #pragma warning disable CS1591
        DailyLimitReached,
        #pragma warning restore CS1591
    }
}
