// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Current status of the export</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetCampaignsByCampaignIdExportByExportIdStatus200ResponseStatusStatus
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "done")]
        #pragma warning disable CS1591
        Done,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
