// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Field data type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetFields200ResponseDataCompanyItemType
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "number")]
        #pragma warning disable CS1591
        Number,
        #pragma warning restore CS1591
        [EnumMember(Value = "boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "datetime")]
        #pragma warning disable CS1591
        Datetime,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
    }
}
