// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Origin of the field</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetFields200ResponseDataContactItemSource
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        DefaultValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "crm_synced")]
        #pragma warning disable CS1591
        CrmSynced,
        #pragma warning restore CS1591
    }
}
