// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetInboxByContactIdDrafts200ResponseDraftsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Communication channel</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemChannel? Channel { get; set; }
        /// <summary>Content preview (max 100 chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentPreview { get; set; }
#nullable restore
#else
        public string ContentPreview { get; set; }
#endif
        /// <summary>Creation date</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Unique draft identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Draft creation source</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemSource? Source { get; set; }
        /// <summary>Draft subject</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Last update date</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItem"/> and sets the default values.
        /// </summary>
        public GetInboxByContactIdDrafts200ResponseDraftsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel", n => { Channel = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemChannel>(); } },
                { "contentPreview", n => { ContentPreview = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemSource>(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemChannel>("channel", Channel);
            writer.WriteStringValue("contentPreview", ContentPreview);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("_id", Id);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetInboxByContactIdDrafts200ResponseDraftsItemSource>("source", Source);
            writer.WriteStringValue("subject", Subject);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
