// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetLeadsByEmail200ResponseSchemaItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Campaign information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemCampaign? Campaign { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemCampaign Campaign { get; set; }
#endif
        /// <summary>Associated contact ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>Enrichment data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemEnrichment? Enrichment { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemEnrichment Enrichment { get; set; }
#endif
        /// <summary>Unique lead identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the lead is paused</summary>
        public bool? IsPaused { get; set; }
        /// <summary>Whether the lead has personalized content</summary>
        public bool? Personalized { get; set; }
        /// <summary>Sending user information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemSendingUser? SendingUser { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemSendingUser SendingUser { get; set; }
#endif
        /// <summary>Source of the lead (e.g., api, csv)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>Current state of the lead (e.g., scanned, contacted)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Current status (e.g., review, done)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Last update timestamp</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Custom variables associated with the lead</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemVariables? Variables { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemVariables Variables { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseSchemaItem"/> and sets the default values.
        /// </summary>
        public GetLeadsByEmail200ResponseSchemaItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseSchemaItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseSchemaItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseSchemaItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaign", n => { Campaign = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemCampaign>(global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemCampaign.CreateFromDiscriminatorValue); } },
                { "contactId", n => { ContactId = n.GetStringValue(); } },
                { "enrichment", n => { Enrichment = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemEnrichment>(global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemEnrichment.CreateFromDiscriminatorValue); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "isPaused", n => { IsPaused = n.GetBoolValue(); } },
                { "personalized", n => { Personalized = n.GetBoolValue(); } },
                { "sendingUser", n => { SendingUser = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemSendingUser>(global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemSendingUser.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "variables", n => { Variables = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemVariables>(global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemVariables.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemCampaign>("campaign", Campaign);
            writer.WriteStringValue("contactId", ContactId);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemEnrichment>("enrichment", Enrichment);
            writer.WriteStringValue("_id", Id);
            writer.WriteBoolValue("isPaused", IsPaused);
            writer.WriteBoolValue("personalized", Personalized);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemSendingUser>("sendingUser", SendingUser);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetLeadsByEmail200ResponseItemVariables>("variables", Variables);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
