// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Email provider</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetUserChannels200ResponseEmailAccountsItemProvider
    {
        [EnumMember(Value = "google")]
        #pragma warning disable CS1591
        Google,
        #pragma warning restore CS1591
        [EnumMember(Value = "microsoft")]
        #pragma warning disable CS1591
        Microsoft,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
