// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetV2CampaignsByCampaignIdStats200ResponseStepsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A/B test variant (if applicable)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AbTest { get; set; }
#nullable restore
#else
        public string AbTest { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of messages bounced</summary>
        public int? Bounced { get; set; }
        /// <summary>Number of clicks from a message from this step</summary>
        public int? Clicked { get; set; }
        /// <summary>Label for conditional steps</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConditionLabel { get; set; }
#nullable restore
#else
        public string ConditionLabel { get; set; }
#endif
        /// <summary>Number of messages delivered</summary>
        public int? Delivered { get; set; }
        /// <summary>Step index in the sequence</summary>
        public int? Index { get; set; }
        /// <summary>Number of LinkedIn invitations sent</summary>
        public int? Invited { get; set; }
        /// <summary>Number of messages not delivered</summary>
        public int? NotDelivered { get; set; }
        /// <summary>Number of messages opened</summary>
        public int? Opened { get; set; }
        /// <summary>Number of replies</summary>
        public int? Replied { get; set; }
        /// <summary>Number of messages sent</summary>
        public int? Sent { get; set; }
        /// <summary>ID of the sequence</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>Step number within the sequence</summary>
        public int? SequenceStep { get; set; }
        /// <summary>Type of task</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItemTaskType? TaskType { get; set; }
        /// <summary>Number of unsubscribes from this step</summary>
        public int? Unsubscribed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItem"/> and sets the default values.
        /// </summary>
        public GetV2CampaignsByCampaignIdStats200ResponseStepsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abTest", n => { AbTest = n.GetStringValue(); } },
                { "bounced", n => { Bounced = n.GetIntValue(); } },
                { "clicked", n => { Clicked = n.GetIntValue(); } },
                { "conditionLabel", n => { ConditionLabel = n.GetStringValue(); } },
                { "delivered", n => { Delivered = n.GetIntValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "invited", n => { Invited = n.GetIntValue(); } },
                { "notDelivered", n => { NotDelivered = n.GetIntValue(); } },
                { "opened", n => { Opened = n.GetIntValue(); } },
                { "replied", n => { Replied = n.GetIntValue(); } },
                { "sent", n => { Sent = n.GetIntValue(); } },
                { "sequenceId", n => { SequenceId = n.GetStringValue(); } },
                { "sequenceStep", n => { SequenceStep = n.GetIntValue(); } },
                { "taskType", n => { TaskType = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItemTaskType>(); } },
                { "unsubscribed", n => { Unsubscribed = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("abTest", AbTest);
            writer.WriteIntValue("bounced", Bounced);
            writer.WriteIntValue("clicked", Clicked);
            writer.WriteStringValue("conditionLabel", ConditionLabel);
            writer.WriteIntValue("delivered", Delivered);
            writer.WriteIntValue("index", Index);
            writer.WriteIntValue("invited", Invited);
            writer.WriteIntValue("notDelivered", NotDelivered);
            writer.WriteIntValue("opened", Opened);
            writer.WriteIntValue("replied", Replied);
            writer.WriteIntValue("sent", Sent);
            writer.WriteStringValue("sequenceId", SequenceId);
            writer.WriteIntValue("sequenceStep", SequenceStep);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.GetV2CampaignsByCampaignIdStats200ResponseStepsItemTaskType>("taskType", TaskType);
            writer.WriteIntValue("unsubscribed", Unsubscribed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
