// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListPersonasModeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "leads")]
        #pragma warning disable CS1591
        Leads,
        #pragma warning restore CS1591
        [EnumMember(Value = "companies")]
        #pragma warning disable CS1591
        Companies,
        #pragma warning restore CS1591
    }
}
