// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchCampaignsByCampaignId200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Automatically detect lead interest</summary>
        public bool? AutoLeadInterest { get; set; }
        /// <summary>Disable out-of-office detection</summary>
        public bool? DisableOutOfOffice { get; set; }
        /// <summary>Disable tracking of link clicks</summary>
        public bool? DisableTrackClick { get; set; }
        /// <summary>Disable tracking of email opens</summary>
        public bool? DisableTrackOpen { get; set; }
        /// <summary>Disable tracking of email replies</summary>
        public bool? DisableTrackReply { get; set; }
        /// <summary>Pause leads based on interest</summary>
        public bool? LeadsPausedByInterest { get; set; }
        /// <summary>The campaign name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Create an opportunity when a lead clicks a link</summary>
        public bool? OpportunityClicked { get; set; }
        /// <summary>Create an opportunity when a lead replies</summary>
        public bool? OpportunityReplied { get; set; }
        /// <summary>Configured senders for the campaign. Only present when sendUserIds was provided in the request. Senders that lack capabilities for any campaign sending channel are excluded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200ResponseSendUsersItem>? SendUsers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200ResponseSendUsersItem> SendUsers { get; set; }
#endif
        /// <summary>Enable sequence sharing for the campaign</summary>
        public bool? SequenceSharing { get; set; }
        /// <summary>Stop the campaign when a lead replies by email</summary>
        public bool? StopOnEmailReplied { get; set; }
        /// <summary>Stop the campaign when a link is clicked</summary>
        public bool? StopOnLinkClicked { get; set; }
        /// <summary>Filter for which link clicks should stop the campaign</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StopOnLinkClickedFilter { get; set; }
#nullable restore
#else
        public string StopOnLinkClickedFilter { get; set; }
#endif
        /// <summary>Stop the campaign when a meeting is booked</summary>
        public bool? StopOnMeetingBooked { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200Response"/> and sets the default values.
        /// </summary>
        public PatchCampaignsByCampaignId200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoLeadInterest", n => { AutoLeadInterest = n.GetBoolValue(); } },
                { "disableOutOfOffice", n => { DisableOutOfOffice = n.GetBoolValue(); } },
                { "disableTrackClick", n => { DisableTrackClick = n.GetBoolValue(); } },
                { "disableTrackOpen", n => { DisableTrackOpen = n.GetBoolValue(); } },
                { "disableTrackReply", n => { DisableTrackReply = n.GetBoolValue(); } },
                { "leadsPausedByInterest", n => { LeadsPausedByInterest = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "opportunityClicked", n => { OpportunityClicked = n.GetBoolValue(); } },
                { "opportunityReplied", n => { OpportunityReplied = n.GetBoolValue(); } },
                { "sendUsers", n => { SendUsers = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200ResponseSendUsersItem>(global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200ResponseSendUsersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sequenceSharing", n => { SequenceSharing = n.GetBoolValue(); } },
                { "stopOnEmailReplied", n => { StopOnEmailReplied = n.GetBoolValue(); } },
                { "stopOnLinkClicked", n => { StopOnLinkClicked = n.GetBoolValue(); } },
                { "stopOnLinkClickedFilter", n => { StopOnLinkClickedFilter = n.GetStringValue(); } },
                { "stopOnMeetingBooked", n => { StopOnMeetingBooked = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoLeadInterest", AutoLeadInterest);
            writer.WriteBoolValue("disableOutOfOffice", DisableOutOfOffice);
            writer.WriteBoolValue("disableTrackClick", DisableTrackClick);
            writer.WriteBoolValue("disableTrackOpen", DisableTrackOpen);
            writer.WriteBoolValue("disableTrackReply", DisableTrackReply);
            writer.WriteBoolValue("leadsPausedByInterest", LeadsPausedByInterest);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("opportunityClicked", OpportunityClicked);
            writer.WriteBoolValue("opportunityReplied", OpportunityReplied);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PatchCampaignsByCampaignId200ResponseSendUsersItem>("sendUsers", SendUsers);
            writer.WriteBoolValue("sequenceSharing", SequenceSharing);
            writer.WriteBoolValue("stopOnEmailReplied", StopOnEmailReplied);
            writer.WriteBoolValue("stopOnLinkClicked", StopOnLinkClicked);
            writer.WriteStringValue("stopOnLinkClickedFilter", StopOnLinkClickedFilter);
            writer.WriteBoolValue("stopOnMeetingBooked", StopOnMeetingBooked);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
