// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>What happens to the lead on reply.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatchCampaignsByCampaignIdRequestOnRepliedCampaignProgress
    {
        [EnumMember(Value = "continue")]
        #pragma warning disable CS1591
        ContinueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
    }
}
