// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchUsersByUserIdLinkedinLimitsRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Max LinkedIn last-post retrievals per day</summary>
        public int? CommentLastPostRetrieveLimit { get; set; }
        /// <summary>Max LinkedIn last-post comments per day</summary>
        public int? CommentLastPostSendLimit { get; set; }
        /// <summary>Max LinkedIn endorsements per day</summary>
        public int? EndorseLimit { get; set; }
        /// <summary>Max LinkedIn follows per day</summary>
        public int? FollowLimit { get; set; }
        /// <summary>Max LinkedIn InMails per day: a daily throttle, the monthly InMail credits of the LinkedIn plan stay the hard cap</summary>
        public int? InMailLimit { get; set; }
        /// <summary>Max LinkedIn invitations per day</summary>
        public int? InviteLimit { get; set; }
        /// <summary>Invite ramp-up: how much the daily invitation limit grows each day until it reaches inviteLimit. null turns the ramp-up off; omit it to keep it as is</summary>
        public int? InviteRampUp { get; set; }
        /// <summary>Max LinkedIn last-post likes per day</summary>
        public int? LikeLastPostLimit { get; set; }
        /// <summary>Max LinkedIn network checks per day</summary>
        public int? NetworkCheckLimit { get; set; }
        /// <summary>Max LinkedIn direct messages per day</summary>
        public int? SendLimit { get; set; }
        /// <summary>Max LinkedIn profile visits per day</summary>
        public int? VisitLimit { get; set; }
        /// <summary>Max LinkedIn invitation withdrawals per day</summary>
        public int? WithdrawInvitationLimit { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchUsersByUserIdLinkedinLimitsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PatchUsersByUserIdLinkedinLimitsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PatchUsersByUserIdLinkedinLimitsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commentLastPostRetrieveLimit", n => { CommentLastPostRetrieveLimit = n.GetIntValue(); } },
                { "commentLastPostSendLimit", n => { CommentLastPostSendLimit = n.GetIntValue(); } },
                { "endorseLimit", n => { EndorseLimit = n.GetIntValue(); } },
                { "followLimit", n => { FollowLimit = n.GetIntValue(); } },
                { "inMailLimit", n => { InMailLimit = n.GetIntValue(); } },
                { "inviteLimit", n => { InviteLimit = n.GetIntValue(); } },
                { "inviteRampUp", n => { InviteRampUp = n.GetIntValue(); } },
                { "likeLastPostLimit", n => { LikeLastPostLimit = n.GetIntValue(); } },
                { "networkCheckLimit", n => { NetworkCheckLimit = n.GetIntValue(); } },
                { "sendLimit", n => { SendLimit = n.GetIntValue(); } },
                { "visitLimit", n => { VisitLimit = n.GetIntValue(); } },
                { "withdrawInvitationLimit", n => { WithdrawInvitationLimit = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("commentLastPostRetrieveLimit", CommentLastPostRetrieveLimit);
            writer.WriteIntValue("commentLastPostSendLimit", CommentLastPostSendLimit);
            writer.WriteIntValue("endorseLimit", EndorseLimit);
            writer.WriteIntValue("followLimit", FollowLimit);
            writer.WriteIntValue("inMailLimit", InMailLimit);
            writer.WriteIntValue("inviteLimit", InviteLimit);
            writer.WriteIntValue("inviteRampUp", InviteRampUp);
            writer.WriteIntValue("likeLastPostLimit", LikeLastPostLimit);
            writer.WriteIntValue("networkCheckLimit", NetworkCheckLimit);
            writer.WriteIntValue("sendLimit", SendLimit);
            writer.WriteIntValue("visitLimit", VisitLimit);
            writer.WriteIntValue("withdrawInvitationLimit", WithdrawInvitationLimit);
        }
    }
}
#pragma warning restore CS0618
