// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchLemwarmByUserMailboxIdSettingsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Percentage of warmup emails that should be answered (0-100)</summary>
        public int? AnswerPercentage { get; set; }
        /// <summary>Percentage of warmup emails sent to internal participants (0-100)</summary>
        public int? InternalCommunicationPercent { get; set; }
        /// <summary>Whether to apply a random daily variance to the warmup email target (spreads volume day-to-day instead of a flat number)</summary>
        public bool? WarmDailyVarianceEnabled { get; set; }
        /// <summary>Maximum number of warmup emails per day (0-40; the server enforces 1-40 unless the team has the lemwarm0limit beta)</summary>
        public int? WarmEmailMax { get; set; }
        /// <summary>Daily increase in the warmup email count (0-40; the server enforces 1-40 unless the team has the lemwarm0limit beta)</summary>
        public int? WarmEmailRampup { get; set; }
        /// <summary>Whether warmup emails are sent as plain text</summary>
        public bool? WarmUsePlaintext { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchLemwarmByUserMailboxIdSettingsRequest"/> and sets the default values.
        /// </summary>
        public PatchLemwarmByUserMailboxIdSettingsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchLemwarmByUserMailboxIdSettingsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PatchLemwarmByUserMailboxIdSettingsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PatchLemwarmByUserMailboxIdSettingsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answerPercentage", n => { AnswerPercentage = n.GetIntValue(); } },
                { "internalCommunicationPercent", n => { InternalCommunicationPercent = n.GetIntValue(); } },
                { "warmDailyVarianceEnabled", n => { WarmDailyVarianceEnabled = n.GetBoolValue(); } },
                { "warmEmailMax", n => { WarmEmailMax = n.GetIntValue(); } },
                { "warmEmailRampup", n => { WarmEmailRampup = n.GetIntValue(); } },
                { "warmUsePlaintext", n => { WarmUsePlaintext = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("answerPercentage", AnswerPercentage);
            writer.WriteIntValue("internalCommunicationPercent", InternalCommunicationPercent);
            writer.WriteBoolValue("warmDailyVarianceEnabled", WarmDailyVarianceEnabled);
            writer.WriteIntValue("warmEmailMax", WarmEmailMax);
            writer.WriteIntValue("warmEmailRampup", WarmEmailRampup);
            writer.WriteBoolValue("warmUsePlaintext", WarmUsePlaintext);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
