// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchDeliverabilityAlertsByAlertIdRequestPeriodMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "rolling")]
        #pragma warning disable CS1591
        Rolling,
        #pragma warning restore CS1591
        [EnumMember(Value = "consecutive")]
        #pragma warning disable CS1591
        Consecutive,
        #pragma warning restore CS1591
    }
}
