// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PatchInboxByContactIdDraftsByDraftIdRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>File attachments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequestAttachmentsItem>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequestAttachmentsItem> Attachments { get; set; }
#endif
        /// <summary>CC email addresses</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cc { get; set; }
#nullable restore
#else
        public List<string> Cc { get; set; }
#endif
        /// <summary>Draft content (max 30KB)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>Activity ID to reply to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToActivityId { get; set; }
#nullable restore
#else
        public string ReplyToActivityId { get; set; }
#endif
        /// <summary>Draft subject</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequest"/> and sets the default values.
        /// </summary>
        public PatchInboxByContactIdDraftsByDraftIdRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequestAttachmentsItem>(global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequestAttachmentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cc", n => { Cc = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "replyToActivityId", n => { ReplyToActivityId = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PatchInboxByContactIdDraftsByDraftIdRequestAttachmentsItem>("attachments", Attachments);
            writer.WriteCollectionOfPrimitiveValues<string>("cc", Cc);
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("replyToActivityId", ReplyToActivityId);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
