// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostCampaigns200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The crm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Crm { get; set; }
#nullable restore
#else
        public string Crm { get; set; }
#endif
        /// <summary>The crmOpportunitiesOnTask property</summary>
        public bool? CrmOpportunitiesOnTask { get; set; }
        /// <summary>The crmUserId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CrmUserId { get; set; }
#nullable restore
#else
        public string CrmUserId { get; set; }
#endif
        /// <summary>The displayedVariableKeys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DisplayedVariableKeys { get; set; }
#nullable restore
#else
        public List<string> DisplayedVariableKeys { get; set; }
#endif
        /// <summary>The emoji property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Emoji { get; set; }
#nullable restore
#else
        public string Emoji { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The inSequenceLeadCount property</summary>
        public int? InSequenceLeadCount { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The reviewedCount property</summary>
        public int? ReviewedCount { get; set; }
        /// <summary>The scannedCount property</summary>
        public int? ScannedCount { get; set; }
        /// <summary>The scheduleIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ScheduleIds { get; set; }
#nullable restore
#else
        public List<string> ScheduleIds { get; set; }
#endif
        /// <summary>The senders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendersItem>? Senders { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendersItem> Senders { get; set; }
#endif
        /// <summary>The sendUsers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendUsersItem>? SendUsers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendUsersItem> SendUsers { get; set; }
#endif
        /// <summary>The sequenceId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The stopOnEmailReplied property</summary>
        public bool? StopOnEmailReplied { get; set; }
        /// <summary>The teamId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The unsubscribe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unsubscribe { get; set; }
#nullable restore
#else
        public string Unsubscribe { get; set; }
#endif
        /// <summary>The variableKeys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseVariableKeysItem>? VariableKeys { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseVariableKeysItem> VariableKeys { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200Response"/> and sets the default values.
        /// </summary>
        public PostCampaigns200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "crm", n => { Crm = n.GetStringValue(); } },
                { "crmOpportunitiesOnTask", n => { CrmOpportunitiesOnTask = n.GetBoolValue(); } },
                { "crmUserId", n => { CrmUserId = n.GetStringValue(); } },
                { "displayedVariableKeys", n => { DisplayedVariableKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "emoji", n => { Emoji = n.GetStringValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "inSequenceLeadCount", n => { InSequenceLeadCount = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reviewedCount", n => { ReviewedCount = n.GetIntValue(); } },
                { "scannedCount", n => { ScannedCount = n.GetIntValue(); } },
                { "scheduleIds", n => { ScheduleIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sendUsers", n => { SendUsers = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendUsersItem>(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendUsersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "senders", n => { Senders = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendersItem>(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sequenceId", n => { SequenceId = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "stopOnEmailReplied", n => { StopOnEmailReplied = n.GetBoolValue(); } },
                { "teamId", n => { TeamId = n.GetStringValue(); } },
                { "unsubscribe", n => { Unsubscribe = n.GetStringValue(); } },
                { "variableKeys", n => { VariableKeys = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseVariableKeysItem>(global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseVariableKeysItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("crm", Crm);
            writer.WriteBoolValue("crmOpportunitiesOnTask", CrmOpportunitiesOnTask);
            writer.WriteStringValue("crmUserId", CrmUserId);
            writer.WriteCollectionOfPrimitiveValues<string>("displayedVariableKeys", DisplayedVariableKeys);
            writer.WriteStringValue("emoji", Emoji);
            writer.WriteStringValue("_id", Id);
            writer.WriteIntValue("inSequenceLeadCount", InSequenceLeadCount);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("reviewedCount", ReviewedCount);
            writer.WriteIntValue("scannedCount", ScannedCount);
            writer.WriteCollectionOfPrimitiveValues<string>("scheduleIds", ScheduleIds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendersItem>("senders", Senders);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseSendUsersItem>("sendUsers", SendUsers);
            writer.WriteStringValue("sequenceId", SequenceId);
            writer.WriteStringValue("state", State);
            writer.WriteBoolValue("stopOnEmailReplied", StopOnEmailReplied);
            writer.WriteStringValue("teamId", TeamId);
            writer.WriteStringValue("unsubscribe", Unsubscribe);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.PostCampaigns200ResponseVariableKeysItem>("variableKeys", VariableKeys);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
