// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>The winning variant</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostSequencesBySequenceIdStepsByStepIdAbTestWinnerRequestVariant
    {
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "B")]
        #pragma warning disable CS1591
        B,
        #pragma warning restore CS1591
    }
}
