// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostCampaignsByCampaignIdStepsByStepIdSkipForLeads200ResponseResultsItemStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "skipped")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
        [EnumMember(Value = "already_skipped")]
        #pragma warning disable CS1591
        AlreadySkipped,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
    }
}
