// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostDeliverabilityAlertsRequestWidget
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "warmup")]
        #pragma warning disable CS1591
        Warmup,
        #pragma warning restore CS1591
        [EnumMember(Value = "outreach")]
        #pragma warning disable CS1591
        Outreach,
        #pragma warning restore CS1591
    }
}
