// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>The type of step to create</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostSequencesBySequenceIdStepsRequestType
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinVisit")]
        #pragma warning disable CS1591
        LinkedinVisit,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinInvite")]
        #pragma warning disable CS1591
        LinkedinInvite,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinSend")]
        #pragma warning disable CS1591
        LinkedinSend,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinVoiceNote")]
        #pragma warning disable CS1591
        LinkedinVoiceNote,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinFollow")]
        #pragma warning disable CS1591
        LinkedinFollow,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinLikeLastPost")]
        #pragma warning disable CS1591
        LinkedinLikeLastPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinCommentLastPost")]
        #pragma warning disable CS1591
        LinkedinCommentLastPost,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinEndorse")]
        #pragma warning disable CS1591
        LinkedinEndorse,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinWithdrawInvitation")]
        #pragma warning disable CS1591
        LinkedinWithdrawInvitation,
        #pragma warning restore CS1591
        [EnumMember(Value = "sendToAnotherCampaign")]
        #pragma warning disable CS1591
        SendToAnotherCampaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "conditional")]
        #pragma warning disable CS1591
        Conditional,
        #pragma warning restore CS1591
        [EnumMember(Value = "whatsappMessage")]
        #pragma warning disable CS1591
        WhatsappMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
    }
}
