// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostV2CampaignsStatsBatchRequestChannelsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedin")]
        #pragma warning disable CS1591
        Linkedin,
        #pragma warning restore CS1591
        [EnumMember(Value = "others")]
        #pragma warning disable CS1591
        Others,
        #pragma warning restore CS1591
    }
}
