// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostWatchlistRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Fully set up and activate the agent. Requires segmentType and signalProcessingType.</summary>
        public bool? Activate { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Emoji shown next to the agent name (defaults to a random emoji)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Emoji { get; set; }
#nullable restore
#else
        public string Emoji { get; set; }
#endif
        /// <summary>Filters to apply (validated against the signal type)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter> Filters { get; set; }
#endif
        /// <summary>Display name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Entity sourcing. Only `all` is supported via the API. Required together with signalProcessingType when activate is true.</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSegmentType? SegmentType { get; set; }
        /// <summary>Task/opportunity template applied to each signal when signalProcessingType is create_opportunity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalOpportunityTemplate? SignalOpportunityTemplate { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalOpportunityTemplate SignalOpportunityTemplate { get; set; }
#endif
        /// <summary>How detected signals are processed</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalProcessingType? SignalProcessingType { get; set; }
        /// <summary>Signal type to monitor</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequest"/> and sets the default values.
        /// </summary>
        public PostWatchlistRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activate", n => { Activate = n.GetBoolValue(); } },
                { "emoji", n => { Emoji = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>(global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "segmentType", n => { SegmentType = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSegmentType>(); } },
                { "signalOpportunityTemplate", n => { SignalOpportunityTemplate = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalOpportunityTemplate>(global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalOpportunityTemplate.CreateFromDiscriminatorValue); } },
                { "signalProcessingType", n => { SignalProcessingType = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalProcessingType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("activate", Activate);
            writer.WriteStringValue("emoji", Emoji);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>("filters", Filters);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSegmentType>("segmentType", SegmentType);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalOpportunityTemplate>("signalOpportunityTemplate", SignalOpportunityTemplate);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestSignalProcessingType>("signalProcessingType", SignalProcessingType);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.PostWatchlistRequestType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
