// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Target status to set on every signal.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PutWatchlistSignalsRequestStatus
    {
        [EnumMember(Value = "handled")]
        #pragma warning disable CS1591
        Handled,
        #pragma warning restore CS1591
        [EnumMember(Value = "ignored")]
        #pragma warning disable CS1591
        Ignored,
        #pragma warning restore CS1591
    }
}
