// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Machine-readable error code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskV2ErrorErrorCode
    {
        [EnumMember(Value = "INVALID_PARAMETER")]
        #pragma warning disable CS1591
        InvalidParameter,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN_FIELD")]
        #pragma warning disable CS1591
        UnknownField,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIELD_TYPE_MISMATCH")]
        #pragma warning disable CS1591
        FieldTypeMismatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_ADVANCED_FILTERS")]
        #pragma warning disable CS1591
        InvalidAdvancedFilters,
        #pragma warning restore CS1591
        [EnumMember(Value = "FILTER_TREE_TOO_COMPLEX")]
        #pragma warning disable CS1591
        FilterTreeTooComplex,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN_SORT_FIELD")]
        #pragma warning disable CS1591
        UnknownSortField,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DATE_RANGE")]
        #pragma warning disable CS1591
        InvalidDateRange,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAGE_OUT_OF_RANGE")]
        #pragma warning disable CS1591
        PageOutOfRange,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEARCH_FAILED")]
        #pragma warning disable CS1591
        SearchFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROUTE_UNAUTHORIZED")]
        #pragma warning disable CS1591
        RouteUnauthorized,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROUTE_BAD_METHOD")]
        #pragma warning disable CS1591
        RouteBadMethod,
        #pragma warning restore CS1591
    }
}
