// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Channel of the task</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskV2Channel
    {
        [EnumMember(Value = "aircall")]
        #pragma warning disable CS1591
        Aircall,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedin")]
        #pragma warning disable CS1591
        Linkedin,
        #pragma warning restore CS1591
        [EnumMember(Value = "whatsapp")]
        #pragma warning disable CS1591
        Whatsapp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
