// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// A record of someone opting out of receiving emails.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Unsubscribe : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Campaign ID from which the person unsubscribed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>Campaign name from which the person unsubscribed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignName { get; set; }
#nullable restore
#else
        public string CampaignName { get; set; }
#endif
        /// <summary>Unsubscribed email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Unique unsubscribe identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Unsubscribe scope</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.UnsubscribeScope? Scope { get; set; }
        /// <summary>Unsubscribe timestamp</summary>
        public DateTimeOffset? UnsubscribedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.Unsubscribe"/> and sets the default values.
        /// </summary>
        public Unsubscribe()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.Unsubscribe"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.Unsubscribe CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.Unsubscribe();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "campaignName", n => { CampaignName = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.UnsubscribeScope>(); } },
                { "unsubscribedAt", n => { UnsubscribedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("campaignName", CampaignName);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("_id", Id);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.UnsubscribeScope>("scope", Scope);
            writer.WriteDateTimeOffsetValue("unsubscribedAt", UnsubscribedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
