// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Lifecycle status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WatchListSchemaStatus
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "insufficient_credits")]
        #pragma warning disable CS1591
        InsufficientCredits,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty_crm_lists")]
        #pragma warning disable CS1591
        EmptyCrmLists,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
    }
}
