// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Filter identifier</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WatchListFilterFilterId
    {
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "location")]
        #pragma warning disable CS1591
        Location,
        #pragma warning restore CS1591
        [EnumMember(Value = "visitLocation")]
        #pragma warning disable CS1591
        VisitLocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "website")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "pagesTracked")]
        #pragma warning disable CS1591
        PagesTracked,
        #pragma warning restore CS1591
        [EnumMember(Value = "minVisitDuration")]
        #pragma warning disable CS1591
        MinVisitDuration,
        #pragma warning restore CS1591
        [EnumMember(Value = "minPageViewed")]
        #pragma warning disable CS1591
        MinPageViewed,
        #pragma warning restore CS1591
        [EnumMember(Value = "internalTraffic")]
        #pragma warning disable CS1591
        InternalTraffic,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinUrls")]
        #pragma warning disable CS1591
        LinkedinUrls,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyLinkedinUrls")]
        #pragma warning disable CS1591
        CompanyLinkedinUrls,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyNames")]
        #pragma warning disable CS1591
        CompanyNames,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyLocation")]
        #pragma warning disable CS1591
        CompanyLocation,
        #pragma warning restore CS1591
        [EnumMember(Value = "companyIndustries")]
        #pragma warning disable CS1591
        CompanyIndustries,
        #pragma warning restore CS1591
        [EnumMember(Value = "companySizes")]
        #pragma warning disable CS1591
        CompanySizes,
        #pragma warning restore CS1591
        [EnumMember(Value = "maxIdentificationsPerDay")]
        #pragma warning disable CS1591
        MaxIdentificationsPerDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "excludedVisitorIps")]
        #pragma warning disable CS1591
        ExcludedVisitorIps,
        #pragma warning restore CS1591
        [EnumMember(Value = "reactionTypes")]
        #pragma warning disable CS1591
        ReactionTypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "linkedinTopics")]
        #pragma warning disable CS1591
        LinkedinTopics,
        #pragma warning restore CS1591
        [EnumMember(Value = "bomboraTopics")]
        #pragma warning disable CS1591
        BomboraTopics,
        #pragma warning restore CS1591
        [EnumMember(Value = "watcherWatchKey")]
        #pragma warning disable CS1591
        WatcherWatchKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "questions")]
        #pragma warning disable CS1591
        Questions,
        #pragma warning restore CS1591
        [EnumMember(Value = "fundraisingMinAmount")]
        #pragma warning disable CS1591
        FundraisingMinAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "fundraisingMaxAmount")]
        #pragma warning disable CS1591
        FundraisingMaxAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "fundraisingInvestmentTypes")]
        #pragma warning disable CS1591
        FundraisingInvestmentTypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "fundraisingInvestors")]
        #pragma warning disable CS1591
        FundraisingInvestors,
        #pragma warning restore CS1591
        [EnumMember(Value = "technologies")]
        #pragma warning disable CS1591
        Technologies,
        #pragma warning restore CS1591
        [EnumMember(Value = "detectionMode")]
        #pragma warning disable CS1591
        DetectionMode,
        #pragma warning restore CS1591
        [EnumMember(Value = "maDealTypes")]
        #pragma warning disable CS1591
        MaDealTypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "maMinAmount")]
        #pragma warning disable CS1591
        MaMinAmount,
        #pragma warning restore CS1591
        [EnumMember(Value = "persona")]
        #pragma warning disable CS1591
        Persona,
        #pragma warning restore CS1591
        [EnumMember(Value = "externalSignalFieldMapping")]
        #pragma warning disable CS1591
        ExternalSignalFieldMapping,
        #pragma warning restore CS1591
        [EnumMember(Value = "externalSignalCustomFieldMapping")]
        #pragma warning disable CS1591
        ExternalSignalCustomFieldMapping,
        #pragma warning restore CS1591
        [EnumMember(Value = "seniority")]
        #pragma warning disable CS1591
        Seniority,
        #pragma warning restore CS1591
        [EnumMember(Value = "crmListIds")]
        #pragma warning disable CS1591
        CrmListIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "minJobCount")]
        #pragma warning disable CS1591
        MinJobCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeframe")]
        #pragma warning disable CS1591
        Timeframe,
        #pragma warning restore CS1591
    }
}
