// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>
    /// A past configuration version of a Signal Agent, active during [startDate, endDate).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WatchListConfigHistoryEntry : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>User id that made the change</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Emoji at capture time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Emoji { get; set; }
#nullable restore
#else
        public string Emoji { get; set; }
#endif
        /// <summary>When this configuration version was replaced</summary>
        public DateTimeOffset? EndDate { get; set; }
        /// <summary>Entity kind</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryEntity? Entity { get; set; }
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter> Filters { get; set; }
#endif
        /// <summary>History entry identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Signal Agent name at capture time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Segment sourcing</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySegmentType? SegmentType { get; set; }
        /// <summary>Signal processing type</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySignalProcessingType? SignalProcessingType { get; set; }
        /// <summary>When this configuration version became active</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Signal/campaign stats computed for the window [startDate, endDate).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryStats? Stats { get; set; }
#nullable restore
#else
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryStats Stats { get; set; }
#endif
        /// <summary>Signal type</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntry"/> and sets the default values.
        /// </summary>
        public WatchListConfigHistoryEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "emoji", n => { Emoji = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetDateTimeOffsetValue(); } },
                { "entity", n => { Entity = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryEntity>(); } },
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>(global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "segmentType", n => { SegmentType = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySegmentType>(); } },
                { "signalProcessingType", n => { SignalProcessingType = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySignalProcessingType>(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "stats", n => { Stats = n.GetObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryStats>(global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryStats.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("emoji", Emoji);
            writer.WriteDateTimeOffsetValue("endDate", EndDate);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryEntity>("entity", Entity);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListFilter>("filters", Filters);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySegmentType>("segmentType", SegmentType);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntrySignalProcessingType>("signalProcessingType", SignalProcessingType);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteObjectValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryStats>("stats", Stats);
            writer.WriteEnumValue<global::Soenneker.Lemlist.OpenApiClient.Models.WatchListConfigHistoryEntryType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
