// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Models
{
    /// <summary>Who the created opportunity is assigned to</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WatchListSchemaSignalOpportunityTemplateOwnerType
    {
        [EnumMember(Value = "contact_owner")]
        #pragma warning disable CS1591
        ContactOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "specific_owner")]
        #pragma warning disable CS1591
        SpecificOwner,
        #pragma warning restore CS1591
    }
}
