// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.Item;
using Soenneker.Lemlist.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Database.SavedSearches
{
    /// <summary>
    /// Builds and executes requests for operations under \database\saved-searches
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SavedSearchesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.database.savedSearches.item collection</summary>
        /// <param name="position">Id of the saved search</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.Item.WithSavedSearchItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.Item.WithSavedSearchItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("savedSearchId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.Item.WithSavedSearchItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavedSearchesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/database/saved-searches{?mode*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavedSearchesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/database/saved-searches{?mode*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the People Database saved searches of your team, sorted by name. Saved searches are team-shared: every member sees the same list.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchListResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 405 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder.SavedSearchesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder.SavedSearchesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchListResponse401Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchListResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a People Database saved search for your team. It shows up in the &quot;Saved searches&quot; menu of the People Database.Filters come from [Get Database Filters](/api-reference/endpoints/people-database/get-database-filters) called with `usage=ui`: a filter not usable in the People Database UI is refused with `FILTER_UNAVAILABLE_FOR_USAGE`, and the error message names the refused filters, comma-separated. Filters incompatible with the `mode` or with your team&apos;s plan are dropped silently; if none remain, the request answers `400`.Only the created id is returned. The stored `name` and `filters` are sanitized and plan-gated server-side, so echoing the request payload back would misreport what was persisted; call [Get Saved Search](/api-reference/endpoints/people-database/get-saved-search) to read the stored saved search.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchCreateResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchCreateResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchCreateResponse?> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.CreateSavedSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchCreateResponse> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.CreateSavedSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchCreateResponse401Error.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Lemlist.OpenApiClient.Models.PersonaError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchCreateResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.SavedSearchCreateResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the People Database saved searches of your team, sorted by name. Saved searches are team-shared: every member sees the same list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder.SavedSearchesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder.SavedSearchesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a People Database saved search for your team. It shows up in the &quot;Saved searches&quot; menu of the People Database.Filters come from [Get Database Filters](/api-reference/endpoints/people-database/get-database-filters) called with `usage=ui`: a filter not usable in the People Database UI is refused with `FILTER_UNAVAILABLE_FOR_USAGE`, and the error message names the refused filters, comma-separated. Filters incompatible with the `mode` or with your team&apos;s plan are dropped silently; if none remain, the request answers `400`.Only the created id is returned. The stored `name` and `filters` are sanitized and plan-gated server-side, so echoing the request payload back would misreport what was persisted; call [Get Saved Search](/api-reference/endpoints/people-database/get-saved-search) to read the stored saved search.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.CreateSavedSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.CreateSavedSearchRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Database.SavedSearches.SavedSearchesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the People Database saved searches of your team, sorted by name. Saved searches are team-shared: every member sees the same list.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SavedSearchesRequestBuilderGetQueryParameters 
        {
            /// <summary>Restrict the list to saved searches of one search mode. Saved searches created before modes existed are returned for both modes. Omit to return every saved search of the team.</summary>
            [QueryParameter("mode")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.ListSavedSearchesModeParameter? Mode { get; set; }
        }
    }
}
#pragma warning restore CS0618
