// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Lemlist.OpenApiClient.Activities;
using Soenneker.Lemlist.OpenApiClient.Campaigns;
using Soenneker.Lemlist.OpenApiClient.Companies;
using Soenneker.Lemlist.OpenApiClient.Contacts;
using Soenneker.Lemlist.OpenApiClient.Crm;
using Soenneker.Lemlist.OpenApiClient.Database;
using Soenneker.Lemlist.OpenApiClient.Deliverability;
using Soenneker.Lemlist.OpenApiClient.Enrich;
using Soenneker.Lemlist.OpenApiClient.Fields;
using Soenneker.Lemlist.OpenApiClient.Hooks;
using Soenneker.Lemlist.OpenApiClient.Inbox;
using Soenneker.Lemlist.OpenApiClient.Leads;
using Soenneker.Lemlist.OpenApiClient.Lemwarm;
using Soenneker.Lemlist.OpenApiClient.Schedules;
using Soenneker.Lemlist.OpenApiClient.Sequences;
using Soenneker.Lemlist.OpenApiClient.Tasks;
using Soenneker.Lemlist.OpenApiClient.Team;
using Soenneker.Lemlist.OpenApiClient.Unsubs;
using Soenneker.Lemlist.OpenApiClient.Unsubscribes;
using Soenneker.Lemlist.OpenApiClient.User;
using Soenneker.Lemlist.OpenApiClient.Users;
using Soenneker.Lemlist.OpenApiClient.V2;
using Soenneker.Lemlist.OpenApiClient.Watchlist;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LemlistOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The activities property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The campaigns property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.CampaignsRequestBuilder Campaigns
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Campaigns.CampaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The crm property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Crm.CrmRequestBuilder Crm
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Crm.CrmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Database.DatabaseRequestBuilder Database
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deliverability property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Deliverability.DeliverabilityRequestBuilder Deliverability
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Deliverability.DeliverabilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enrich property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Enrich.EnrichRequestBuilder Enrich
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Enrich.EnrichRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fields property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Fields.FieldsRequestBuilder Fields
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Fields.FieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hooks property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Hooks.HooksRequestBuilder Hooks
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Hooks.HooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inbox property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Inbox.InboxRequestBuilder Inbox
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Inbox.InboxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leads property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Leads.LeadsRequestBuilder Leads
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Leads.LeadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lemwarm property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Lemwarm.LemwarmRequestBuilder Lemwarm
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Lemwarm.LemwarmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schedules property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder Schedules
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sequences property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Sequences.SequencesRequestBuilder Sequences
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Sequences.SequencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder Team
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Team.TeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unsubs property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Unsubs.UnsubsRequestBuilder Unsubs
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Unsubs.UnsubsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unsubscribes property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Unsubscribes.UnsubscribesRequestBuilder Unsubscribes
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Unsubscribes.UnsubscribesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.V2.V2RequestBuilder V2
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The watchlist property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Watchlist.WatchlistRequestBuilder Watchlist
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Watchlist.WatchlistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.LemlistOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LemlistOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.lemlist.com/api";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
