// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps
{
    /// <summary>
    /// Builds and executes requests for operations under \campaigns\{campaignId}\leads\{leadIdOrEmail-id}\steps
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StepsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.campaigns.item.leads.item.steps.item collection</summary>
        /// <param name="position">The unique identifier of the step, from GET /campaigns/{campaignId}/sequences</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.Item.WithStepItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.Item.WithStepItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("stepId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.Item.WithStepItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.StepsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StepsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/leads/{leadIdOrEmail%2Did}/steps", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Campaigns.Item.Leads.Item.Steps.StepsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StepsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaigns/{campaignId}/leads/{leadIdOrEmail%2Did}/steps", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
