// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Sequences.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sequences\{sequenceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSequenceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The steps property</summary>
        public global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.StepsRequestBuilder Steps
        {
            get => new global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.Steps.StepsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.WithSequenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSequenceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences/{sequenceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Sequences.Item.WithSequenceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSequenceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sequences/{sequenceId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
