// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Lemlist.OpenApiClient.Models;
using Soenneker.Lemlist.OpenApiClient.Schedules.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Lemlist.OpenApiClient.Schedules
{
    /// <summary>
    /// Builds and executes requests for operations under \schedules
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchedulesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Lemlist.OpenApiClient.schedules.item collection</summary>
        /// <param name="position">The unique identifier of the schedule</param>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.Item.WithScheduleItemRequestBuilder"/></returns>
        public global::Soenneker.Lemlist.OpenApiClient.Schedules.Item.WithScheduleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("scheduleId", position);
                return new global::Soenneker.Lemlist.OpenApiClient.Schedules.Item.WithScheduleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/schedules{?limit*,offset*,page*,sortBy*,sortOrder*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchedulesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/schedules{?limit*,offset*,page*,sortBy*,sortOrder*}", rawUrl)
        {
        }
        /// <summary>
        /// Get Many Schedules
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.ScheduleListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.ScheduleListResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.ScheduleListResponse401Error">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.ScheduleListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.ScheduleListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Schedules.ScheduleListResponse400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Schedules.ScheduleListResponse401Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.ScheduleListResponse>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.ScheduleListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create Schedule
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Models.Schedule"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedules400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedules401Response">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.Schedule?> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedulesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Lemlist.OpenApiClient.Models.Schedule> PostAsync(global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedulesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedules400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedules401Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Lemlist.OpenApiClient.Models.Schedule>(requestInfo, global::Soenneker.Lemlist.OpenApiClient.Models.Schedule.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Many Schedules
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder.SchedulesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create Schedule
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedulesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Lemlist.OpenApiClient.Models.PostSchedulesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Lemlist.OpenApiClient.Schedules.SchedulesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Many Schedules
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SchedulesRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of records to return</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The number of records to skip. Used if page is not provided.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>The page number to retrieve</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The field by which to sort the schedules. Currently, only &apos;createdAt&apos; is supported.</summary>
            [QueryParameter("sortBy")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.CreatedAtSortBy? SortBy { get; set; }
            /// <summary>The sort direction. Use &apos;desc&apos; for descending order; any other value (or omission) will sort in ascending order.</summary>
            [QueryParameter("sortOrder")]
            public global::Soenneker.Lemlist.OpenApiClient.Models.GetSchedulesSortOrderParameter? SortOrder { get; set; }
        }
    }
}
#pragma warning restore CS0618
